default_config:

tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes

sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation

#group: !include groups.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml
